/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 *
 * @author Windows HD
 */
public class formaMain extends javax.swing.JDialog {

    /**
     * Creates new form formaMain
     */
    public formaMain(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        meniKlubovi = new javax.swing.JMenu();
        meniTakmicenja = new javax.swing.JMenu();
        meniUtakmice = new javax.swing.JMenu();
        meniRezultati = new javax.swing.JMenu();
        menija = new javax.swing.JMenu();
        meniStatistika = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setMaximumSize(new java.awt.Dimension(400, 280));
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 280));
        jLabel2.setRequestFocusEnabled(false);

        meniKlubovi.setText("Klubovi");
        meniKlubovi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meniKluboviMouseClicked(evt);
            }
        });
        jMenuBar1.add(meniKlubovi);

        meniTakmicenja.setText("Takmičenja");
        meniTakmicenja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meniTakmicenjaMouseClicked(evt);
            }
        });
        jMenuBar1.add(meniTakmicenja);

        meniUtakmice.setText("Utakmice");
        meniUtakmice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meniUtakmiceMouseClicked(evt);
            }
        });
        jMenuBar1.add(meniUtakmice);

        meniRezultati.setText("Rezultati");
        meniRezultati.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meniRezultatiMouseClicked(evt);
            }
        });
        jMenuBar1.add(meniRezultati);

        menija.setText("Igrači");
        menija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menijaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menija);

        meniStatistika.setText("Statistika");
        meniStatistika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meniStatistikaMouseClicked(evt);
            }
        });
        jMenuBar1.add(meniStatistika);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meniKluboviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meniKluboviMouseClicked
        JPanel panel = new formaKlubovi();
        JDialog dialog = new JDialog();
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.getContentPane().setBackground(Color.red);
        dialog.setTitle("Forma - Dodaj Novi Klub");
    }//GEN-LAST:event_meniKluboviMouseClicked

    private void meniTakmicenjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meniTakmicenjaMouseClicked
        JPanel panel = new formaTakmicenja();
        JDialog dialog = new JDialog();
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.getContentPane().setBackground(Color.red);
        dialog.setTitle("Forma - Dodaj Novo Takmičenje");
    }//GEN-LAST:event_meniTakmicenjaMouseClicked

    private void meniUtakmiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meniUtakmiceMouseClicked
        JPanel panel = new formaUtakmice();
        JDialog dialog = new JDialog();
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.getContentPane().setBackground(Color.red);
        dialog.setTitle("Forma - Dodaj Novu Utakmicu");
    }//GEN-LAST:event_meniUtakmiceMouseClicked

    private void meniRezultatiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meniRezultatiMouseClicked
        JPanel panel = new formaRezultati();
        JDialog dialog = new JDialog();
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.getContentPane().setBackground(Color.red);
        dialog.setTitle("Forma - Dodaj Novi Rezultat");
    }//GEN-LAST:event_meniRezultatiMouseClicked

    private void menijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menijaMouseClicked
        JPanel panel = new formaIgraci();
        JDialog dialog = new JDialog();
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.getContentPane().setBackground(Color.red);
        dialog.setTitle("Forma - Dodaj Novog Igrača");
    }//GEN-LAST:event_menijaMouseClicked

    private void meniStatistikaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meniStatistikaMouseClicked
        JPanel panel = new formaStatistike();
        JDialog dialog = new JDialog();
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.getContentPane().setBackground(Color.red);
        dialog.setTitle("Forma - Dodaj Novu Statistiku");
    }//GEN-LAST:event_meniStatistikaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                formaMain dialog = new formaMain(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu meniKlubovi;
    private javax.swing.JMenu meniRezultati;
    private javax.swing.JMenu meniStatistika;
    private javax.swing.JMenu meniTakmicenja;
    private javax.swing.JMenu meniUtakmice;
    private javax.swing.JMenu menija;
    // End of variables declaration//GEN-END:variables
}
